menu:
  Home: /
  Archives: archives

widgets:
- search
- category
- tag
- archive

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

fancybox: true

google_analytics: G-R32CHMGLNE
rss: emublog

comment_provider: disqus
# Disqus comment
disqus_shortname: mu-blog-1
# Facebook comment
facebook:
  appid: # <appId>
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
